name: Build, test, check with Clippy, and check formatting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust (Stable)
        run:
          curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Install Clippy
      run: rustup component add clippy
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Build project
      run: cargo build --verbose
    - name: Test project
      run: cargo test --verbose
    - name: Check with Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Check formatting
      run: cargo fmt -- --check
